// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqRgSpwMWpXqhAYro1GPKpq-BnWrJ-7Q',
    appId: '1:328485139159:web:56377e90e59b0ea84cb692',
    messagingSenderId: '328485139159',
    projectId: 'dinner-duck',
    authDomain: 'dinner-duck.firebaseapp.com',
    storageBucket: 'dinner-duck.firebasestorage.app',
    measurementId: 'G-PK4T0QFPS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJxDapX02jdmzT4scNHZuduGq0G9Q2l9U',
    appId: '1:328485139159:android:05a18d533c14be0e4cb692',
    messagingSenderId: '328485139159',
    projectId: 'dinner-duck',
    storageBucket: 'dinner-duck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV84u5goz4SR6EePOAXivz_17ltuDDoFs',
    appId: '1:328485139159:ios:2a51d708682a7d0b4cb692',
    messagingSenderId: '328485139159',
    projectId: 'dinner-duck',
    storageBucket: 'dinner-duck.firebasestorage.app',
    iosBundleId: 'com.example.dinnerDuck',
  );
}
